language: rust
sudo: required
dist: trusty

rust:
  - stable
  - nightly
  - beta

cache: cargo

addons:
  postgresql: "9.5"
  apt:
    packages:
      - libssl-dev

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - cargo install diesel_cli --no-default-features --features=postgres || echo "diesel_cli already installed."

before_script:
  - echo "DATABASE_URL=postgres://postgres@localhost/hamster" > .env
  - diesel setup

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

after_success:
  # Codecov
  - |
    if [[ "$TRAVIS_RUST_VERSION" ==  "nightly" ]]; then
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
    fi
