language: rust
sudo: required
dist: trusty

cache:
  apt: true
  cargo: true

matrix:
  include:
    - rust: stable
    - rust: nightly
    - rust: beta
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
  - cargo clean && cargo test --all

after_success:
  # Codecov
  - |
    if [[ "$TRAVIS_RUST_VERSION" ==  "nightly" ]]; then
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
    fi
