[package]
name = "hamster-api"
edition = "2018"
version = "0.0.0"
authors = ["yanhai <shimmly@live.cn>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/Dokuro-YH/hamster-rs"

[dependencies]
